only change autoscan on wlan that shares the same phy80211 in hostapd…
firewalla/firerouter pull request #896
Opened 2022-11-02 09:42 UTC by jasonlyc

…_plugin.js

2022-11-02 11:33 UTC, drahnieR requested changes

2022-11-02 11:33 UTC, drahnieR commented on plugins/interface/wlan_intf_plugin.js
> +      console.error(`No wlan interface configured with wpa_supplicant`);
`this.log.error` ?

2022-11-03 02:31 UTC, jasonlyc commented on plugins/interface/wlan_intf_plugin.js
> +      console.error(`No wlan interface configured with wpa_supplicant`);
this.log is not available in static function

2022-11-03 03:24 UTC, drahnieR approved these changes

2022-11-03 04:19 UTC, merged